services:
  # Node.js/Express Backend API
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    container_name: flowbit-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./packages/api:/app
      - /app/node_modules
      - ./registry.json:/app/registry.json
    depends_on:
      - mongo

  # React Shell UI (Port 3000)
  shell-ui:
    build:
      context: ./packages/shell-ui
      dockerfile: Dockerfile
    container_name: flowbit-shell-ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./packages/shell-ui:/app
      - /app/node_modules

  # Support Tickets MFE (Port 3001)
  support-tickets-mfe:
    build:
      context: ./packages/support-tickets-mfe
      dockerfile: Dockerfile
    container_name: flowbit-mfe-support
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./packages/support-tickets-mfe:/app
      - /app/node_modules

  # MongoDB Database Service
  mongo:
    image: mongo:latest
    container_name: flowbit-mongo
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
