services:
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    container_name: flowbit-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./packages/api:/app
      - /app/node_modules
      - ./registry.json:/app/registry.json
    depends_on:
      - mongo

  shell-ui:
    build:
      context: ./packages/shell-ui
      dockerfile: Dockerfile
    container_name: flowbit-shell-ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./packages/shell-ui:/app
      - /app/node_modules

  support-tickets-mfe:
    build:
      context: ./packages/support-tickets-mfe
      dockerfile: Dockerfile
    container_name: flowbit-mfe-support
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./packages/support-tickets-mfe:/app
      - /app/node_modules

  # N8N SERVICE
  n8n:
    image: n8nio/n8n
    container_name: flowbit-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file: ./.env
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      - api

  mongo:
    image: mongo:latest
    container_name: flowbit-mongo
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  n8n-data: